version: "3.8"

x-extra_hosts:
  &default-extra_hosts
  - "db_mssql:$DB_MSSQL"
  - "testing_db_mssql:$TESTING_DB_MSSQL" 
  - "app_server:$APP_SERVER"
  - "{{ frontend.dns.api }}:$API_GATEWAY"
  - "{{ frontend.dns.frontend }}:$PORTAL_GATEWAY"
  - "{{ frontend.dns.cdn }}:$CDN_GATEWAY"

networks:
  servicos:
    external:
      name: servicos

services:
  viasoft-relatorios:
    image: "{{ docker_account }}/viasoft.relatorios:1.3.x{{ docker_image_suffix }}"
    container_name: "Viasoft.Relatorios"
    restart: on-failure:10
    extra_hosts: *default-extra_hosts
    environment:
      - ON_PREMISE_MODE=true
      - USE_SERVERGC={{ use_servergc }}
      - URL_CONSUL=http://consul-server:8500
      - CERT_FILE_PATH={{ self_signed_ca_cert_path }}
    networks:
      - servicos
    volumes:
      - "{{ self_signed_certs_directory }}/:{{ self_signed_certs_directory }}/"

  viasoft-reporting-pivottable:
    image: "{{ docker_account }}/viasoft.reporting.pivottable:1.2.x{{ docker_image_suffix }}"
    container_name: "Viasoft.Reporting.PivotTable"
    restart: on-failure:10
    extra_hosts: *default-extra_hosts
    environment:
      - ON_PREMISE_MODE=true
      - USE_SERVERGC={{ use_servergc }}
      - URL_CONSUL=http://consul-server:8500
      - CERT_FILE_PATH={{ self_signed_ca_cert_path }}
    networks:
      - servicos
    volumes:
      - "{{ self_signed_certs_directory }}/:{{ self_signed_certs_directory }}/"
  
  viasoft-relatorios-agendador:
    image: "{{ docker_account }}/viasoft.relatorios.agendador:1.2.x{{ docker_image_suffix }}"
    container_name: "Viasoft.Relatorios.Agendador"
    restart: on-failure:10
    extra_hosts: *default-extra_hosts
    environment:
      - ON_PREMISE_MODE=true
      - USE_SERVERGC={{ use_servergc }}
      - URL_CONSUL=http://consul-server:8500
      - CERT_FILE_PATH={{ self_signed_ca_cert_path }}
    networks:
      - servicos
    volumes:
      - "{{ self_signed_certs_directory }}/:{{ self_signed_certs_directory }}/"
